name: app_asegurate
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"



  

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  cupertino_icons: ^1.0.2
  blur: ^3.1.0
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^5.1.0
  dio: ^4.0.6
  logger: ^1.1.0
  get_it: ^7.2.0
  liquid_progress_indicator_ns: ^1.0.0
  tutorial_coach_mark: ^1.2.4
  app_tutorial: ^0.3.2
  flutter_markdown: ^0.6.12
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  get: ^4.6.5
  file_picker: ^4.6.1
  flutter_carousel_slider: ^1.0.9
  image_picker: ^0.8.5+3
  get_storage: ^2.0.3

  flutter_dotenv: ^5.0.2
  encrypt: ^5.0.1
  jwt_decoder: ^2.0.1
  hexcolor: ^2.0.5
  sn_progress_dialog: ^1.0.8
  dart_code_metrics: ^4.19.1
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/privacy_policy.md
    - assets/images/
    - .env

  fonts:
    - family: TradeGothicInline
      fonts:
        - asset: assets/fonts/TradeGothicInline-Light.ttf
        - asset: assets/fonts/TradeGothicInline-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  
