name: app_asegurate
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  get: ^4.6.5
  http: ^0.13.5
  file_picker: ^4.6.1
  flutter_carousel_slider: ^1.0.9

  shimmer: ^2.0.0

  hexcolor: ^2.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: TradeGothicInline
      fonts:
        - asset: assets/fonts/TradeGothicInline-Light.ttf
        - asset: assets/fonts/TradeGothicInline-Regular.ttf

